### ISSUE TITLE
website

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/ods2022#11]
Il template è https://preview.uideck.com/items/grand/

## task

- [x] dominio di terzo livello https://ods2022.opendatasicilia.it/
- [x] fix timer
- [x] fix navbar color
- [x] fix hero
- [x] definire struttura (home, cos'è, ~cosa faremo~, chi siamo, comitato, _iscriviti_ (da sostituire con _registrati_ o viceversa)
- [x] aggiungere [contenuti](https://docs.google.com/document/d/1QpjHmueNZBRAAycLSxyLvlo0VBCkLl-TAsoWNMGAnl0/edit?pli=1)
- [x] open graph ref
- [x] url
  - [x] eventbrite https://www.eventbrite.it/e/biglietti-ods2022-dati-e-potere-il-raduno-2022-di-open-data-sicilia-385755183137
  - [x] form talk
  - [x] form workshop

**Comment by gpirrotta** [comment]
Aggiornato il sito Web ODS2022 con i primi contenuti.

**Comment by dennisangemi** [comment]
Ciao @gpirrotta , @angelogulina ho aggiornato un paio di cosette nel sito. Mi servirebbe una mano per fixare il timer: come si fa partire? lol

Qualcuno può darci un'occhiata? Grazie!

**Comment by gabacode** [comment]
Ciao @dennisangemi ho aggiornato la data del countdown al 30 Settembre 2022

**Comment by dennisangemi** [comment]
Ciao @gpirrotta e grazie per le modifiche che stai apportando al sito. Di seguito alcune note che mi vengono in mente:
- che ne dici di spostare la sezione "chi siamo" dopo "cos'è"? Potremmo ampliare "chi siamo" sulla base di quanto scritto nella presentazione della comunità e alla fine inserirei anche l'emedding del video di ODS2021 così come da #15 . Se per te è ok, posso provare ad inserirlo io ;)
- credo che la barra con i buttons per i social network sia eccessivamente invadente (per quanto riguarda la versione desktop). Inoltre modificherei il colore rendendolo coerente con #10 . Per questo ultimo punto chiederei un tuo intervento perchè io non sono in grado di mettere mano alla barra ihih
